/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --config wrangler.toml --include-runtime false` (hash: eede10a16b26c10170b857603a75a763)
declare namespace Cloudflare {
	interface Env {
		THUMBNAILS: R2Bucket;
		DB: D1Database;
		SYNC_STALE_AFTER_SECONDS: "90";
		NINA_SESSION_BASE_URL: string;
		NINA_ADVANCED_API_BASE_URL: string;
		SYNC_API_BASE_URL: string;
		SYNC_HMAC_SECRET: string;
		SYNC_INTERVAL_MS: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SYNC_STALE_AFTER_SECONDS" | "NINA_SESSION_BASE_URL" | "NINA_ADVANCED_API_BASE_URL" | "SYNC_API_BASE_URL" | "SYNC_HMAC_SECRET" | "SYNC_INTERVAL_MS">> {}
}
