/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --config wrangler.toml --include-runtime false` (hash: a39201b08ee42a403a599c5f32ac42b3)
declare namespace Cloudflare {
	interface Env {
		THUMBNAILS: R2Bucket;
		DB: D1Database;
		SYNC_STALE_AFTER_SECONDS: "90";
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SYNC_STALE_AFTER_SECONDS">> {}
}
