name = "astro-site"
compatibility_date = "2026-03-12"
compatibility_flags = ["nodejs_compat"]

keep_vars = true

[[d1_databases]]
binding = "DB"
database_name = "astro-site"
database_id = "fa54c98e-3196-4958-b0be-7e78154472f6"
migrations_dir = "drizzle"

[[r2_buckets]]
binding = "THUMBNAILS"
bucket_name = "astro-site-thumbnails"

[vars]
SYNC_STALE_AFTER_SECONDS = "90"
